import type { Metadata } from "next";
import { useEffect, useState } from "react";
import Navbar from "./Organisms/Navbar";
import Footer from "./Organisms/Footer";

export const metadata: Metadata = {
  title: "Green Hills Academy",
  description: "Generated by Green Hills Academy",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <div>
        <Navbar />
        {children}
        <Footer />
      </div>
    </div>
  );
}
